[package]
name = "ui_id"
version = "0.4.1"
authors = ["Bryan Woods"]
edition = "2021"

[lib]
proc-macro = true


[dependencies]
syn = "2.0"
quote = "1.0"
fastrand = "2.2"


[dev-dependencies]
itertools = "0.13.0"
